In [3]:
import numpy as np

In [4]:
arr=np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [5]:
print(arr.shape)
print(arr.ndim)
print(arr.size)

(5,)
1
5


Matrix creation (2x3)

In [6]:
mat=np.array([[1,2,3],[4,5,6]])
print(mat)

[[1 2 3]
 [4 5 6]]


In [7]:
print(mat.shape)
print(mat.ndim)
print(mat.size)

(2, 3)
2
6


Special Arrays creation

a) 3*3 zero matrix

In [9]:
zero_mat=np.zeros((3,3))
zero_mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

b)2*4 ones matrix

In [10]:
one_mat=np.ones((2,4))
one_mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

c)array range

In [11]:
my_range=np.arange(0,20,5)
my_range

array([ 0,  5, 10, 15])

Vectorized operations

In [13]:
arr1=np.array([5,10,15,20])
print(arr1*2)
print(arr1+5)
print(arr1**2)

[10 20 30 40]
[10 15 20 25]
[ 25 100 225 400]


Aggregation functions

In [14]:
mean=np.mean(arr1)
total=np.sum(arr1)
mini=np.min(arr1)
maxi=np.max(arr1)
print(f"Mean is {mean}")
print(f"Sum of values is {total}")
print(f"Minimum value is {mini}")
print(f"Maximum value is {maxi}")

Mean is 12.5
Sum of values is 50
Minimum value is 5
Maximum value is 20


In [17]:
sd=np.std(arr1)
print(f"Standard deviation is {sd}")

Standard deviation is 5.5901699437494745


Mini task: create array of student marks, find avg marks, highest marks, lowest marks, addd 5 bonus marks to all students

In [18]:
marks=np.array([87,95,65,73,81,78])
avg_marks=np.sum(marks)/marks.size
highest=np.max(marks)
lowest=np.min(marks)
new_marks=marks+5
print(f"Average marks is {avg_marks}")
print(f"Highest marks is {highest}")
print(f"Lowest marks is {lowest}")
print(f"Adding 5 marks: {new_marks}")

Average marks is 79.83333333333333
Highest marks is 95
Lowest marks is 65
Adding 5 marks: [ 92 100  70  78  86  83]
